### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by sfhmzpig** [MSKCC-Epi-Bio/dcurves#27]
when install dcurves, occure a error: 
statsmodels/tsa/_innovations.c:22820:45: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
      22820 |     const digit* digits = ((PyLongObject*)b)->ob_digit;
            |                                             ^~
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
and then throw: Failed to build statsmodels

my python env is py12

**Comment by shaunporwal** [comment]
I just released dcurves 1.1.1 which is compatible with Python 3.12, can you try it out and see if it fixed the issue?

**Comment by sfhmzpig** [comment]
I use new version try again, and is work. ths
